== postgres

=== Run a docker container

----
docker run --name postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres
----


=== Setup

.Install
----
$ sudo apt-get install postgresql
----

.Setup

.Edit postgresql.conf (/etc/postgresql/9.5/main/postgresql.conf) to set the listen address
----
listen_addresses = '*'
----

.Edit pg_hba.conf (/etc/postgresql/9.5/main/pg_hba.conf) to allow remote access
----
host    all             all             192.168.1.0/24           trust
----
TIP: Depending on your installation environment you might need to add another network range.

. Restart
. Set password for postgres user
----
$ sudo -u postgres psql postgres
postgres=# \password postgres
----

=== Create user and database using SQL
. Connect as postgres:postgres
. Create the user
+
[source,sql]
----
CREATE USER registry PASSWORD 'registry' createdb;
----
. Create database
+
[source,sql]
----
CREATE DATABASE registry OWNER = registry;
----

=== Create user and database using command
. Create the user
+
----
createuser -h <host> -U <user_to_connect_as> <new_user>
----
+
.Example
----
createuser -h localhost -U postgres registry_qa
----
+
. Create the database
+
----
createdb -h <host> -O <new_database_owner> -U <user_to_connect_as> <new_database>
----
+
.Example:
----
createdb -h localhost -O registry -U registry registry_qa
----

=== Backup
----
pg_dump -U <user_to_connect_as> -W -F t <database_to_dump> > <dump.tar>
----
.Example
----
pg_dump -U registry -W -F t registry > registry.tar
----
=== Restore

----
pg_restore -h <host> -U <user_to_connect_as> -d <database_to_restore_to> -C -W <dump.tar>
----

.Example
----
pg_restore -h localhost -U registry -d registry_qa -C -W registry.tar
----

.To restore a database into an existing one
----
pg_restore -h localhost -d registry_test -U postgres registry-20161113.tar
----

=== Miscellaneous

.Find database version
----
select version();
----

.Connect to postgres
----
psql --host=localhost --port=5432 --username=postgres
----

.Show all databases
After connecting as `postgres` (database super user):
----
postgres=# \list
----
TIP: Shortcut: `\l`

.Drop database
After connecting as `postgres` (database super user):
----
