== PI Camera
The *PI Camera* is a small hardware module that can be hooked on a Raspberry PI

=== Streaming video
Using the PI Camera, video can be streamed from the camera _(Raspberry PI)_ to another system _(a linux host)_ through the network.

.On the linux host
First a listening socket must be established on the linux host. The Linux host must have installed *mplayer* and *netcat* in order to receive and decode the video.

----
$ nc -l 9898 | mplayer -fps 24 -demuxer h264es -
----

* *-l 9898*: listen on port 9898
* *-fps 24*: frames per second
* *-demuxer h264es* : demux using h264es
* *-* : input should be standard input

.On the Raspberry PI
----
$ raspivid -t 0 -w 1280 -h 720 -rot 180 -fps 24 -o - | nc 192.168.1.3 9898
----

* *-t 0* : stream indefinetily
* *-w 1280* : width of the video will be 1280
* *-h 720* : height of the video will be 720
* *-fps* : frames per second
* *-o -* : output to stdout (don't miss the -)

The standard output of Raspberry PI pipes its output to netcat, which in this case establishes a connection to _192.168.1.1.3_ on port 9898

CAUTION: The stream is **unencrypted**, and possibly anyone in between the Raspbery and the linux host can intercept it (man in the middle).

=== Using encryption
Using *ssh* facilities, one can encrypt the stream, and as a bonus, control the whole procedure from the linux host without having to log into the Raspberry PI interactively. Additionally, if _ssh key authentication_ is configured, then this is by far the most comfortable way to stream.

----
$ ssh user@raspberry "raspivid -t 0 -w 1280 -h 720 -rot 180 -fps 24 -o -" | mplayer -fps 24 -demuxer h264es -
----

Maybe this command requires a little explanation for the new ssh users. The syntax _ssh user@raspberry command_,  invokes *command* at *raspberry* as *user*. The command output will be printed to the standard output of the linux host.

If using as command, *raspivid* with the same parameters used in the previous example, the stream will be output to our standard output. By piping this output to mplayer standard input, you get the same effect of the previous method, but this time encrypted!

[TIP]
====
To store the stream as a file too, use *tee*:

----
$ ssh user@raspberry "raspivid -t 0 -w 1280 -h 720 -rot 180 -fps 24 -o -" | tee stream.h264 | mplayer -fps 24 -demuxer h264es -
----

And to playback:
----
$ mplayer -fps 24 -demuxer h264es stream.h264
----
====
